name: Shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo as string
        run: echo "hello world"
      - name: multiline
        run: |
          node -v
          npm -v
